vultr_vps: ENC[AES256_GCM,data:puPeYwTj+2GiFikMhrr4mHt10Vq+fQwblpM+zVdr7Z3PjAHi9oOdSH31jNdPFRp9yDK3v6WLL0aE4GkYkckeNgC0idM3Y5rA8ZGaer6UDslBpmeSD2V8obYhB8k8Ay7DE4ZHMjmxWoj5Iny0xJymyJxZUpvZg5D6S9agfYver8xRYjwidqk6n0SuWO2HiE+AUfUaqCy0zOjR2dvOsBbo1UTgXaOHV0jBseU1jRct6tzr9PbLJhQ1Wr4xqlPNJVTrTxOVm/Hzuwcrnruq76snkq/KFouan6p8/iRZH+qsdsGbkFpwto9wnQkQIy9aVb0jFRUl3uNRxK2Pi0yjLdI+6VQ=,iv:+sK8/wAJhE7LfimISojMN8e/OAjjiCNB2JTmlzQ75QY=,tag:XcytOpNLiriGvKcOrGKWow==,type:str]
tapfog_link: ENC[AES256_GCM,data:GS6Q8QZM/8sPc5t+L/8HCPgu7et5FBvTOcQ79u3Jh+B9BYNEpHK6IN1ilV9qzn6Ks6cC5smri7MlTPT6svCF0OqpqYUvA7K1XYiSDppd3Jq5w3xpf3+t1vI=,iv:77X5awEHyWxDbBqtFrkMCnacTvpLoL8kVt4AAoAdDOI=,tag:CdTFHDiDcz/HCtepOxROsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMmVEZ0xwekIrQmdSSmRs
            UzBKMGJNcG02dFVuTjdvSld5ZEdOU3k5NFhZCnU1Nk5QK2NzbUlEUkt1UU9VMXdV
            cXFMZGtYYmJSQ1duTnRUek83ZmFId1UKLS0tIFphOHVScDU1bTZ1TVZRbXZTS1NS
            dWFHWjBWRmZiMXRvaHZuRDVvVmtrNVkKr0usS9f84/J/sumnDx15pjnBnFaZUFAr
            C/DuRwGLTDI5+0IbY82iY7dKRSgyWMlDtOJa8osvnhAJaI1XhW4pqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1745vunna3pmzt5m39m7kuag6ppc5a032s3wlhdy0xmyvv3ddrphst23ld5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTStETkVQV3NxVW1EcHZt
            VEhLUk1iQTcxM05CbnRTaTZldWlFdG5peDBnCnplWmlSM1R6ZWJzUGJmdWZIWDJC
            WVg3eGR1M1pCQ2ZLN0o5V3RoRjF6RGcKLS0tIG52WlRkcDh2eStEMHBEelZxb3VX
            QWF0QWZzN3pWdGtrd1FzdmN4OVlwK3MKqcSgq5eUFOoZdMx8OPIeF2Z8Bju1uwnr
            M7ZPsaxTeXQK3FBsL2I9GhMwETJYgi99i6YwxHl7MqsyeZe8xapNLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14nnrz58sle0hlhvszd26ke4s5vqkrfl95yu2rkz5gu8hx5kgvq3se6d29n
    lastmodified: "2026-09-15T11:36:52Z"
    mac: ENC[AES256_GCM,data:L6+j4xg81CX2Ba4o/7PDtMG7IOkFLPut5BevZa7cjTxXMpB1DvDSgGM1U4OWd5CPiykkNneI9vJjdLmlxSoIXkPYjAWQaBJ3omcB8JTdYmugtlOJ0QdkLkkODqxlrq5xWS0S1utW4Fhq6hHm5qehdZIQG8KpnDrdATXudxspT/Y=,iv:7b5FPI61M+LKvcHRiGAlLNNxiB2vV96pFDbTfdVWswg=,tag:fB/rwm9FglrBXTqv4RWRGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
